title: Cloud Lab
description: Portfolio técnico de 2.º ASIR
lang: es
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
student_name: David Omedes
student_group: 2.º ASIR
github_url: https://github.com/david706/cloud-lab-omedesd.git
progress: 10
exclude:
  - README.md
  - GUIA_ALUMNO.md
